/**
 * Catch all error that throws from a runner function
 *
 * @param {Function} fn
 * @return {Function}
 */
export declare function handleError(fn: (...args: any) => Promise<any>): (...args: any) => void;
